# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-07 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('parent_id', models.CharField(blank=True, max_length=36, null=True)),
                ('owner_user_id', models.IntegerField(blank=True, null=True)),
                ('owner_group_id', models.IntegerField(blank=True, null=True)),
                ('uploader_id', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(max_length=6)),
                ('name', models.CharField(max_length=255)),
                ('size', models.BigIntegerField()),
                ('is_public', models.IntegerField(default=0)),
                ('is_starred', models.IntegerField(default=0)),
                ('is_trashed', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('root_folder', models.CharField(max_length=36)),
                ('invite_code', models.CharField(max_length=36)),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='GroupUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('joined_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=50)),
                ('root_folder', models.CharField(max_length=36)),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
