# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-13 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khubox', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=77),
        ),
    ]
