# Generated by Django 3.0.7 on 2020-06-09 17:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('group_name', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('owner_email', models.EmailField(max_length=254)),
                ('group_users', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Group User')),
            ],
        ),
    ]
